FROM jupyter/minimal-notebook:latest
RUN /opt/conda/bin/conda install -c conda-forge nb_conda_kernels nbgitpuller jupyter-archive nodejs nglview && \
    jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build && \
    jupyter labextension install nglview-js-widgets
COPY jupyter_notebook_config.py /etc/jupyter/jupyter_notebook_config.py
