FROM jupyter/minimal-notebook:latest
ENV MKL_NUM_THREADS=1 \
    OMP_NUM_THREADS=1
#RUN /opt/conda/bin/conda install -c conda-forge nb_conda_kernels nbgitpuller jupyter-archive nodejs nglview && \
#    jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build && \
#    jupyter labextension install nglview-js-widgets
#RUN /opt/conda/bin/conda install -c conda-forge minepy
RUN python -m pip install --no-cache-dir pycalphad==0.10.1 espei==0.8.9 scheil==0.1.6 kawin==0.1.2 nbgitpuller
COPY jupyter_notebook_config.py /etc/jupyter/jupyter_notebook_config.py
