FROM jupyter/minimal-notebook:latest
ENV MKL_NUM_THREADS=1 \
    OMP_NUM_THREADS=1
RUN /opt/conda/bin/conda install -c conda-forge cxx-compiler
RUN python -m pip install --no-cache-dir pysipfenn==0.12.0 pycalphad==0.10.2 espei==0.8.9 scheil==0.1.6 kawin==0.2.0 scikit-learn nbgitpuller ipywidgets
RUN python -c "from pysipfenn import Calculator; Calculator().downloadModels()"
COPY jupyter_notebook_config.py /etc/jupyter/jupyter_notebook_config.py
