
name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Dockerfile.lab
        run: docker build --file Dockerfile.lab --tag richardotis/jupyterlab-image:${GITHUB_SHA::8} .
      - name: Push Dockerfile.lab
        run: docker push richardotis/jupyterlab-image:${GITHUB_SHA::8}
